### ISSUE TITLE
Unable to find instrumentation info for: ComponentInfo{com.samuel.myapplication.test/android.support.test.runner.AndroidJUnitRunner}

### ISSUE THREAD

**Issue by samuelltk** [whuhan2013/mywebproject#2]
com.samuel.myapplication.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.samuel.myapplication.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.samuel.myapplication.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Am.runInstrument(Am.java:1105)
	at com.android.commands.am.Am.onRun(Am.java:373)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:102)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)

**Comment by whuhan2013** [comment]
https://testerhome.com/topics/2098
